version: "3"
services:
  mongo:
    image: mongo:latest
    hostname: mongodb
    volumes:
      - ./docker/initdb.d/:/docker-entrypoint-initdb.d/
      - ${MONGO_PERSISTENT_STORAGE_DB}/:/data/db/
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: admin
    ports:
      - "27017:27017"
#  web-gui:
#    hostname: web-gui
#    build: web-gui
#    environment:
#      MONGO_HOST: mongodb
#      MONGO_PORT: 27017
#    ports:
#      - "5000:80"
