version: "3"
services:
  mongo:
    image: mongo:latest
    volumes:
      - ./docker/initdb.d/:/docker-entrypoint-initdb.d/
      - ${MONGO_PERSISTENT_STORAGE_DB}:/data/db/
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: admin
    ports:
      - "27017:27017"
    command: ['--replSet', 'rs', '--bind_ip_all']
  web-gui:
    build: web-gui
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
    ports:
      - "5000:80"
    depends_on:
      - mongo
  quote-updater:
    #    image: amplication/scheduler
    # build:
    #   context: 'https://github.com/kpk-pl/amplication.git#:packages/amplication-scheduler'
    # volumes:
    #   - ./docker/schedule.json:/etc/scheduler/config
    build: docker/quote-updater
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    environment:
      QUOTE_UPDATER_METHOD: PUT
      QUOTE_UPDATER_URI: http://web-gui/quotes/
      TZ: "Europe/Warsaw"
      QUOTE_UPDATER_SCHEDULE: "21:20"
    depends_on:
      - web-gui
